### ISSUE TITLE
Error when I import the package

### ISSUE THREAD

**Issue by NoobiCodi** [AppPear/ChartView#11]
Hello
I installed the package, and it worked, but when i wrote :
```swift
import SwiftUICharts
```
I got this error :
`No such module 'SwiftUICharts'`

**Comment by AppPear** [comment]
Please check out the demo code it's working there
https://github.com/AppPear/ChartViewDemo

**Comment by mehmet0zen** [comment]
I just added the package and everything seems fine but when I type
`import SwiftUICharts`
it gives me the same error: No such module 'SwiftUICharts'
