### ISSUE TITLE
BarChartView style in dark mode didn't respect set up

### ISSUE THREAD

**Issue by Petr-2019** [AppPear/ChartView#118]
```
BarChartView(data: ChartData(values: [("cool",1918), ("cool",11991), ("cool",13260), ("cool",14539), ("cool",16539)]), title: "HP", style: Styles.barChartStyleNeonBlueDark, form: ChartForm.medium)
```

## Description
The color is always orange in dark mode (But switch to light mode, this issue is fixed)

## Expected Behavior
The color should be blue

## Actual Behavior
The color is always orange

![Screen Shot 2020-06-24 at 10 33 56 PM](https://user-images.githubusercontent.com/7663073/85576987-72ae4180-b66b-11ea-9c41-7130f7125099.png)

## Your Environment

* Version of this package used: 1.5.1
* Device/Simulator: iPhone 11 Pro, 13.5
* Operating System and version: Xcode 11.5, mac os 10.15.5

**Comment by Petr-2019** [comment]
```
self.darkModeStyle = style.darkModeStyle != nil ? style.darkModeStyle! : Styles.barChartStyleOrangeDark
```

Seems like a intented behavior rather than a bug

**Comment by satan87** [comment]
Duplicate for #72.
You find the right solution;) To force the color in DarkMode you need to set them up manually.
It will be fixed in V2.

**Comment by Petr-2019** [comment]
Thanks for the response, I'll close this one.
