### ISSUE TITLE
Support for UIKit

### ISSUE THREAD

**Issue by syedrazackimran** [AppPear/ChartView#119]
I would like to use your library.

## Description

I'm using UIKit, not an SwiftUI. I really don't know how to implement with to my project. If you have any sample thing kindly share to it will really help for me.

I found some solution with UIHostingController 

That's also I really i don't know to pass data to LineChart(). Kindly do needfully and thanks in advance

## Your Environment

* Version of this package used:
* Device/Simulator:
* Operating System and version:
* Link to your project:

**Comment by AppPear** [comment]
Sorry no support for UIKit, and there will be none in the future. I believe there are many great open source projects for displaying charts in UIKit
