### ISSUE TITLE
AppPear/ChartView on CocoaPods

### ISSUE THREAD

**Issue by patpatpat123** [AppPear/ChartView#12]
Hello,

First of all, wanted to say, this is an awesome project.
As of now, well explained from the README, we need to install this project by doing:

In xCode got to File -> Swift Packages -> Add Package Dependency and paste inthe repo's url: https://github.com/AppPear/ChartView

Would it make more sense to have some sort of management with CocoaPods, or Carthage and such instead?

Thank you

**Comment by AppPear** [comment]
SwiftUI works on xCode 11 and zou have built in swift package manager in xCode 11 for mac os, iOS, watchOS so I don't see the point of using another package manager too.

**Comment by dev-danries** [comment]
https://github.com/dev-danries/ChartView-Cocoapods
