### ISSUE TITLE
XCode 12 beta support

### ISSUE THREAD

**Issue by Cgaafary** [AppPear/ChartView#125]
I tried importing via SwiftPM using Xcode 12 beta and it doesn't work. 

I'm getting this error:
Module compiled with Swift 5.2.4 cannot be imported by the Swift 5.3 compiler

Wondering if Swift 5.3 and Xcode 12 beta compatibility is planned at any point in the near future.

**Comment by AppPear** [comment]
I drafted a new release should be supporting xcode 12 now
