### ISSUE TITLE
Closure containing control flow statement cannot be used with function builder 'ViewBuilder'

### ISSUE THREAD

**Issue by MaanasPeri23** [AppPear/ChartView#126]
I added the Package Dependency (" https://github.com/AppPear/ChartView") in XCode. I am currently using XCode 11, and IOS 13.4, but I'm getting the "No such module 'SwiftUICharts'" described above after importing 'SwiftUICharts' in my ContentView. 

After a little bit more digging, I'm finding the error described in the MultiLineChartsView on Line 88 'if let rateValue = rateValue' 

Would someone please help me out? 

## Your Environment

* Version of this package used:
* Device/Simulator:
* Operating System and version:
* Link to your project:

**Comment by Guillaume351** [comment]
Hello,
I'm having the same issue on Xcode 11.5

**Comment by midashuang** [comment]
Hi,
I'm having the same issue on Xcode 11.5

**Comment by vlourme** [comment]
I just submitted a potential fix to the issue. I did not tried other Xcode version, but it seems that `if let` closure are not accepted anymore in Views. So, I replaced by default value to `0`.

**Comment by MaanasPeri23** [comment]
Hey, I'm still getting the same error when I imported the package dependency. Would you mind looking into this further?
