### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by Pergamon256** [AppPear/ChartView#130]
## Description
Getting "No such module 'SwiftUICharts'" error when trying to import via `import SwiftUICharts` in ContentView.swift. Installed the package according to the instructions on the readme, and the demo project linked in the readme gives the same error. Any help is much appreciated.

**Comment by Gabiik96** [comment]
Install version 1.5.1
1.5.2 is for XCode 12, I guess you are trying to run it on 11
