### ISSUE TITLE
lineview does not reach the line and cropped.

### ISSUE THREAD

**Issue by Max-Job** [AppPear/ChartView#132]
## Description

value does not match the graph. as you can see in the screenshot, the graph (value 7) does not reach the line. also, the second screenshot shows that the chart is cropped.

## Your Environment

* Version of this package used: 1.5.3
* Device/Simulator: simulator iPhone 11
* Operating System and version: ios 13.5

* Link to your project:

![iPhone 11 (13 5) 2020-07-07 14-04-32](https://user-images.githubusercontent.com/58559377/86771647-43300980-c05b-11ea-9839-60c356108974.png)
![iPhone 11 (13 5) 2020-07-07 14-06-16](https://user-images.githubusercontent.com/58559377/86771653-462afa00-c05b-11ea-8aa8-08dc01a35dec.png)

**Comment by janbildsoehansen** [comment]
i have same issues on my build i get this on some of my charts too
