### ISSUE TITLE
Requesting Ability to Change Line Graph Card Width

### ISSUE THREAD

**Issue by bcorrel2** [AppPear/ChartView#139]
For my current project, I require a line chart that fills a card the width of the screen. This library looks amazing and is the best one I can find, but the card-based line chart is too narrow for my preferences. I've tried the full screen line chart as well but it doesn't seem to play nicely with cards. Ideally I'd want to stretch the card-based line chart to fill the screen.

**Comment by AppPear** [comment]
Hi V2 beta 1 supports that
