### ISSUE TITLE
Option to remove cornerRadius 4.0 from BarChart

### ISSUE THREAD

**Issue by jojost1** [AppPear/ChartView#145]
# v2 ticket

## Ticket description:
The BarChart has a hardcoded `RoundedRectangle(cornerRadius: 4)`. I think it's better to remove the cornerRadius property to have more freedom in the look of the graph. It can make labels and spacing look a bit strange.

Example:
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-07-28 at 09 34 37](https://user-images.githubusercontent.com/8880568/88633665-996df680-d0b5-11ea-936a-3506163afef9.png)

**Comment by AppPear** [comment]
I pushed a fix for this to the new-version (v2) branch. When you set no shadow for the cardview I disabled corner masking

**Comment by jojost1** [comment]
That's great, thanks!
