### ISSUE TITLE
If data array contains 0, LineView have crashes

### ISSUE THREAD

**Issue by ramzzzay** [AppPear/ChartView#16]
How to reproduce:

`LineView(data: [5,8,23,54,0,12,37,7,23,43], title: "Line chart")`

**Comment by AppPear** [comment]
added a quick fix for it but as of now it can only display values 0 and above. Will add support for negative numbers as well soon

**Comment by AppPear** [comment]
Solved, now works perfectly for negative and floating point numbers too
