### ISSUE TITLE
Slack invite link in readme not working

### ISSUE THREAD

**Issue by shreyaspapi** [AppPear/ChartView#164]
The invite like of slack in the readme of the project is not working.

**Comment by WikipediaBrown** [comment]
Same does

**Comment by shreyaspapi** [comment]
Any updates on this?

**Comment by AppPear** [comment]
https://join.slack.com/t/swiftuichartview/shared_invite/zt-g6mxioq8-j3iUTF1YKX7D23ML3qcc4g

**Comment by AppPear** [comment]
join here please, thanks! :)
