### ISSUE TITLE
Support Chart Labels

### ISSUE THREAD

**Issue by AmeddahAchraf** [AppPear/ChartView#166]
# Detailed Description

It would be better if the chart displays a generated scale from the given data on the Y Axis or both
## Context
It can be beneficial for improving the chart overall display

<img width="584" alt="Screen Shot 2020-09-24 at 9 15 12 AM" src="https://user-images.githubusercontent.com/33070929/94119189-76a65700-fe46-11ea-9ffb-372d0124bfd4.png">

**Comment by JackMoseley2001** [comment]
I would also like this to become a feature - it would allow for much more detailed charts. 

+1
