### ISSUE TITLE
Linecharts not drawing lines

### ISSUE THREAD

**Issue by magicmikek** [AppPear/ChartView#172]
For the line chart the Path is not drawing anymore.

## Description

After updating Xcode the line charts do not draw lines anymore. 

## Expected Behavior

Line Chart should show lines in the chart.
## Actual Behavior

No lines. 
![Screenshot 2020-10-22 at 14 11 49](https://user-images.githubusercontent.com/7288679/96870002-8ed2bb80-1470-11eb-94f9-9d548c39c30e.png)
## Possible Fix

🤷
## Steps to Reproduce

Run the demo project with the newest version of Xcode. 

## Your Environment

* Version of this package used:
Running the latest demo version.
* Device/Simulator:
iPhone 11
* Operating System and version:
10.15.7 
* Link to your project:

**Comment by kdthomas2121** [comment]
@magicmikek will this PR be merged soon?

**Comment by magicmikek** [comment]
> @magicmikek will this PR be merged soon?

Not sure..

**Comment by Rokania** [comment]
Lines are actually not drawing in Xcode and simulator but it's actually drawing on my real phone
