### ISSUE TITLE
Unable to add labels in bar chart

### ISSUE THREAD

**Issue by Omrisha** [AppPear/ChartView#18]
How can I do this?

**Comment by AppPear** [comment]
<img width="268" alt="Screenshot 2019-11-21 at 17 51 18" src="https://user-images.githubusercontent.com/2826764/69358766-ae24ff80-0c87-11ea-9ffb-658f7b8c50a0.png"> Which label?

**Comment by Omrisha** [comment]
Hi,

Label for each bar that describe it.

Thanks,
Omri

**Comment by Omrisha** [comment]
Label for each bar that describe it.

**Comment by bmaciag** [comment]
Would also need some kind of X/Y Legend like date and value

**Comment by davidhodge** [comment]
I just wanted to add that I'd also love to see this. Specially, labels for each X value, but ideally also some Y axis labels like you have for the line chart!

**Comment by AppPear** [comment]
Check out 1.4.6
