### ISSUE TITLE
Updating the chart data

### ISSUE THREAD

**Issue by greymattermack** [AppPear/ChartView#21]
Hey,

I am currently doing: 

LineView(data: self.insightData.chart.balances, dates: self.insightData.chart.dates)
        
self.insightData is a  @published variable. 

When the value of variable changes the chart crashes. Here is the error I keep getting.

<img width="1394" alt="Screen Shot 2019-11-25 at 10 47 48 PM" src="https://user-images.githubusercontent.com/6855367/69597965-bce81b00-0fd5-11ea-9e04-ec353c938a3f.png">

**Comment by AppPear** [comment]
Thanks, I'll investigate!

**Comment by kurmetaubanov** [comment]
facing the same issue

**Comment by AppPear** [comment]
Fixed
