### ISSUE TITLE
ChartVIew structs not present in beta

### ISSUE THREAD

**Issue by dudenamedjune** [AppPear/ChartView#228]
# v2 ticket

## Ticket description:
<img width="447" alt="Screen Shot 2021-11-30 at 11 25 38 PM" src="https://user-images.githubusercontent.com/8673104/144176957-7ae1c337-60af-4f4c-9c7a-8b4f112ef5f7.png">

**Comment by AppPear** [comment]
please check this tutorial https://github.com/AppPear/ChartView/wiki/How-to-create-your-first-chart
