### ISSUE TITLE
Form Redeclaration

### ISSUE THREAD

**Issue by gacrichards** [AppPear/ChartView#23]
I love this library and have uses it to jump start charting in a few of my apps. I recently was pulling my hair out trying to build a Form in an app that implements this library. I had a flaky and vague build issue (Argument passed to call that takes no arguments) whenever I tried to wrap views in a Form (SwiftUI form). I tracked the issue to a redeclaration of the struct Form in the Helpers.swift file in this library. Please rename this struct so it doesn't break SwiftUI Forms.

**Comment by AppPear** [comment]
Hi, sure I'll do a refactor
