### ISSUE TITLE
in 2.0.0-beta.2, BarChartView is gone. 

### ISSUE THREAD

**Issue by no13bus** [AppPear/ChartView#232]
BarChartView(data: ChartData(values: [("2018 Q4",63150), ("2019 Q1",50900), ("2019 Q2",77550), ("2019 Q3",79600), ("2019 Q4",92550)]), title: "Sales", legend: "Quarterly")
this code has error in version 2.0.0-beta.2. the error is  `Cannot find 'BarChartView' in scope`

## Expected Behavior

BarChartView should not have bugs

## Your Environment

* Version of this package used: 2.0.0-beta.2
* Device/Simulator: iphone13 pro
* Operating System and version: macos 12.0.1 
* Link to your project:

**Comment by AppPear** [comment]
please check this https://github.com/AppPear/ChartView/wiki/How-to-create-your-first-chart
