### ISSUE TITLE
App Crashes when following the How to create your first chart

### ISSUE THREAD

**Issue by YoelL** [AppPear/ChartView#234]
Followed the Beta 2 how to page and got a crash.

## Description
Console Message:
SwiftUI/EnvironmentObject.swift:70: Fatal error: No ObservableObject of type ChartStyle found. A View.environmentObject(_:) for ChartStyle may be missing as an ancestor of this view.

## Expected Behavior
See a line/ bar chart

## Actual Behavior
App crashes

## Steps to Reproduce
Follow this:  https://github.com/AppPear/ChartView/wiki/How-to-create-your-first-chart

## Your Environment

* Version of this package used:  exact 2.0.0-beta.2
* Device: iPhone 12 Pro
* Operating System and version: 12.1 (21C52) - Xcode 13.2.1 (13C100) 
* Link to your project:

**Comment by YoelL** [comment]
<img width="731" alt="Screen Shot 2022-01-19 at 12 25 22" src="https://user-images.githubusercontent.com/11230042/150112167-09d85d2e-c4ea-44e6-b688-8e979bb17cdb.png">
<img width="2424" alt="Screen Shot 2022-01-19 at 12 25 08" src="https://user-images.githubusercontent.com/11230042/150112174-8fddbd1e-2205-44aa-b362-8e1c1d3e7c32.png">

**Comment by kashif-izhar** [comment]
@YoelL I see that you closed this issue. What was the resolution? I am having the same crash.

**Comment by HengJayWang** [comment]
I have the same crash situation ...

**Comment by HengJayWang** [comment]
> @YoelL I see that you closed this issue. What was the resolution? I am having the same crash.

I think the .chartStyle( ) modifier must need  to add.

**Comment by YoelL** [comment]
Hi, yes it was probably that.
