### ISSUE TITLE
ChartView fatal error drawing legend

### ISSUE THREAD

**Issue by timmyhadwen** [AppPear/ChartView#24]
Hi,

Getting this error when giving it data:

Fatal error: Unexpectedly found nil while unwrapping an Optional value: file

![image](https://user-images.githubusercontent.com/4350849/70383194-7de29e00-19b5-11ea-94b5-a347ba0c093a.png)

**Comment by timmyhadwen** [comment]
Seems to be caused by using negative numbers in the data set....

**Comment by AppPear** [comment]
Hi I'm aware of this issue I'll push a fix to it soon when I'll have time for it See also #16

**Comment by AppPear** [comment]
Fixed, works now with negative numbers, and doubles too
