### ISSUE TITLE
Cannot convert value of type '[Double]' to expected argument type '[Int]'

### ISSUE THREAD

**Issue by lisindima** [AppPear/ChartView#28]
Hi, after updating to the latest version (1.4.3) this error appeared. Xcode 11.3 (11C29).
<img width="1279" alt="Снимок экрана 2019-12-28 в 12 26 12" src="https://user-images.githubusercontent.com/43087859/71539339-85bab000-296d-11ea-9b82-e6d1d6aa7bc1.png">

**Comment by iRick92** [comment]
This PR might fix the problem: https://github.com/AppPear/ChartView/pull/29

**Comment by AppPear** [comment]
Thanks merged it!
