### ISSUE TITLE
Error in Beta 5, PieChartCell 

### ISSUE THREAD

**Issue by jufabeck2202** [AppPear/ChartView#3]
When I use the Libary in Beta 5, I get an Error inside the path Computed Properties in the PieChartCell Struct. It will crash the Application

**Comment by kimbauters** [comment]
Not the problem of this library, all to do with beta 5:

**Known Issues**
Using the Path structure may cause your app to crash if you’re using the SDKs included in Xcode 11 beta 5. As a result, you may be unable to successfully follow the steps in the Drawing Paths and Shapes tutorial. (53523206)

**Comment by jufabeck2202** [comment]
Thanks for the info
