### ISSUE TITLE
Line isn't graphed properly for specific values

### ISSUE THREAD

**Issue by ThasianX** [AppPear/ChartView#31]
Given the array, `[0.6137386018237082, 0.2815539332538736, 0.17518342474101156, 0.24931948665991222, -1.1515280464216635, 1.1460104011887073, 0.2818422889043964, -1.3491616766467065, 1.5056442831215968, 0.6401420838971583, -56.699696969696966]`, of values, I get the following graph

<img width="197" alt="Screen Shot 2019-12-30 at 2 55 29 PM" src="https://user-images.githubusercontent.com/20830930/71604003-6d38ca00-2b14-11ea-8955-7e0ab979abaf.png">

Some content is clipped off. I looked at the source code and it has something to do with step height.

**Comment by AppPear** [comment]
Hi, check out 1.4.5 brand new jsut for you fixed the clipping please test it!
