### ISSUE TITLE
Alternating bar colors

### ISSUE THREAD

**Issue by wildfang** [AppPear/ChartView#38]
Hello,
what would be the smartest way to build a graph that compares two values and show each bar in a different color?

Thanks and kind regards

**Comment by AppPear** [comment]
I would overlay 2 `BarChartRow` components in a ZStack and offset the front a bit so you can see the second one too

**Comment by wildfang** [comment]
That's a good idea, thanks! But would it be possible to edit the bar's spacing so I could place them next to each other?

**Comment by AppPear** [comment]
oh in that case you can define the 2 colors you want to alternate 

```swift
var color1
var color2

 ForEach(0..<self.data.count) { i in
                    BarChartCell(
...
                    accentColor: i%2 == 0 ? color1 : color2,
                    secondGradientAccentColor:  i%2 == 0 ? color1 : color2,
...
```

and you don't need in this case 2 BarChartRow component
