### ISSUE TITLE
LineChartView indicator point in wrong position 

### ISSUE THREAD

**Issue by xspyhack** [AppPear/ChartView#39]
Test data: [11, 3, 2, 5, 29, 9]
![Screen Shot 2020-01-21 at 12 07 02 PM](https://user-images.githubusercontent.com/5518285/72774757-c04efa00-3c46-11ea-9480-fb8c2b02da33.png)

**Comment by AppPear** [comment]
This is a fundamental issue. The way I calculate the position by nature is off. So here is how I do it: 

```swift
func getClosestPointOnPath(touchLocation: CGPoint) -> CGPoint {
        let percentage:CGFloat = min(max(touchLocation.x,0)/self.frame.width,1)
        let closest = self.path.percentPoint(percentage)
        return closest
}
```

So basically I take the touch location and normalise it in the frame of the chartview, so for example if your touch is in the middle the value is 0.5
I take the length of the linechart path and put the indicator point at a distance 0.5*length

So if the linechart path is wavy it'll be off

I didn't found yet a at least the same efficient method to display it correctly so if someone has one please comment below or do a PR or both! 😊

**Comment by xspyhack** [comment]
The `Path.trimmedPath(from:to:)` use the path real length to trim path, not frame.width, so the percentage should be
`lengthFromBeginToTouchPointOfX / totalLength`.
I will do a PR to fix this issue.

**Comment by AppPear** [comment]
Thanks!
