### ISSUE TITLE
LineView in dark mode

### ISSUE THREAD

**Issue by Andreasgejlm** [AppPear/ChartView#41]
As of now, the LineView always has a black background if the device is in dark mode. This is a problem if the chart is to be put on a different colored background (or simply a modal presented sheet).
Would you consider an option to add a dark mode background color as well?

**Comment by Yonodactyl** [comment]
Hello,

Right inside the documentation it describes how to use a different style. Make sure you look it over as it's full of helpful stuff!
```swift
let chartStyle = ChartStyle(backgroundColor: Color.black, accentColor: Colors.OrangeStart, secondGradientColor: Colors.OrangeEnd, chartFormSize: ChartForm.medium, textColor: Color.white, legendTextColor: Color.white )
 ...
 BarChartView(data: [8,23,54,32,12,37,7,23,43], title: "Title", style: chartStyle)
```

**Comment by Andreasgejlm** [comment]
Thanks for replying. In LineView.swift, you set the background color of the chart with
`Rectangle().foregroundColor(self.colorScheme == .dark ? Color.black : self.style.backgroundColor)`

In this case, the background color will be black in dark mode, or am I missing something?

**Comment by Yonodactyl** [comment]
Well, you would have to use a color that can adjust with dark mode.
If you set a color to black it will always be black. You can create your own color set inside the assets folder or you can use a color that already adjust with Dark Mode, for example:
`.systemBackground` or `.systemBlue`

Have you tried implementing a style with the code from my previous comment?

**Comment by Andreasgejlm** [comment]
That won't make a difference since it's set to black explicitly when colorScheme is .dark.
Yes, I did try it out. I can see however, that the BarView uses the chosen background color, even in dark mode, which is not the case for LineView.
I'm only talking about LineView, as the BarView functions as intended.

**Comment by Yonodactyl** [comment]
You have two options here, my friend:
1. You can send in a PR so that it takes in a `UIColor` value instead of `Color` - that's not necessary, though.
2. Create your own colors using a custom `Color` initializer like so:

`Color(UIColor.systemBackground)`

You will notice this now changes with the environment of the device. In this, you can also create custom colors in the assets folder. Here is a full implementation:

```swift
let chartStyle = ChartStyle(backgroundColor: Color(UIColor.systemBackground), accentColor: Color(UIColor.systemBlue), secondGradientColor: Color(UIColor.systemPurple), textColor: Color(UIColor.label), legendTextColor: Color(UIColor.secondaryLabel))
    var body: some View {
        VStack{
            LineChartView(data: [8,23,54,32,12], title: "Title", style: chartStyle)
        }
    }
```

**Comment by Andreasgejlm** [comment]
That's still plain wrong. I'm not talking about the LineChartView, it's the LineView that has the non-optional black background in dark mode.
What I'm suggesting is:
`Rectangle().foregroundColor(self.style.backgroundColor)`
instead of:
`Rectangle().foregroundColor(self.colorScheme == .dark ? Color.black : self.style.backgroundColor)`

As of right now, no matter what color you pass as a backgroundColor, be it a system color or not, the lineView will always have a black background in dark mode, as can be seen in the ternary operator in the current implementation.
In LineChartView and BarChartView, this ternary operator is not present, and the background will change depending on your set color in dark mode. The LineView does not.

**Comment by Yonodactyl** [comment]
Hello,
I am sorry that i repeatedly kept misunderstanding you. I see now what you mean. I have forked the project and have removed the check for the colorScheme of the application and have changed the color freely as you can see below.

<img src="https://user-images.githubusercontent.com/18172931/73981240-d673e000-48ff-11ea-987f-c6c07f7a5098.png" width="300" height="649.6">

I would suggest that you submit a PR with a better method for background color selection if you think you can come up with a good idea.

**Comment by Andreasgejlm** [comment]
No problem, just a misunderstanding 👍

**Comment by AppPear** [comment]
I created a new feature which allows you to specify a darkMode style if you are creating a custom style so please use that
