### ISSUE TITLE
ForEach(_:content:)` should only be used for *constant* data.

### ISSUE THREAD

**Issue by schooltech** [AppPear/ChartView#44]
When using ObservedObject data, errors like below:

`
@ObservedObject var dashboardDataModel: DashboardDataModel
......
BarChartView(data: ChartData(points: self.dashboardDataModel.response.data.pastThirtyDayChecksArray ),
                                 title: "Checks",
                                 form: ChartForm.medium, dropShadow: false
                    )

......
onAppear {
      self.dashboardDataModel.fetchData()
}
`
the error:
`
ForEach<Range<Int>, Int, ModifiedContent<ModifiedContent<BarChartCell, _ScaleEffect>, _TransactionModifier>> count (30) != its initial count (0). `ForEach(_:content:)` should only be used for *constant* data. Instead conform data to `Identifiable` or use `ForEach(_:id:content:)` and provide an explicit `id`!
`

**Comment by ftlno** [comment]
Is there any change here?
