### ISSUE TITLE
Support for negative numbers in chart.

### ISSUE THREAD

**Issue by maxbogus** [AppPear/ChartView#45]
Test data:
LineView(data: [-2,1,0,2,-1,-2,1,0,-2,1,0,2,-1,-2,1,0,-2,1,0,2,-1,-2,1,0,-2], title: "title", legend: "legend")
Expected result: LineChart is correctly shown.
Actual result: All bars are shown in the upper part of chart.

**Comment by AppPear** [comment]
Hi, barchart not yet currently support negative numbers, it's coming soon, till you can display negative values with linechart which should correctly display

**Comment by maxbogus** [comment]
I found problems with linechart, if gap between upper and lower numbers is small. For example -2 ... 2

**Comment by AppPear** [comment]
I see, I think I found the fix for it I just pushed so check out the next release
