### ISSUE TITLE
Support for WatchOS

### ISSUE THREAD

**Issue by SaurabhPrajapati** [AppPear/ChartView#5]
Hi buddy,

**Issue:-** I was unable to import this library to WatchOS Extension.

I have tried this awesome library. just want you to add support for watchOS too.

Thanks,
Saurabh Prajapati

**Comment by AppPear** [comment]
Added watchOS support for bar chart

**Comment by SaurabhPrajapati** [comment]
Hey @AppPear 

This was nice to see watchOS support for barChart.

Can you please also check for other types of charts to support WatchOS?

Thanks,
Saurabh Prajapati
