### ISSUE TITLE
Dark Mode Labels incorrect

### ISSUE THREAD

**Issue by rmbeaty** [AppPear/ChartView#51]
The text color of the labels is not correct in Dark Mode. Looks like it is white text on a white background. I have attached a picture to show what I mean.

[Image](https://drive.google.com/open?id=1onVRKctrxr6CTwnbbpmaaQNkfj6EnDwC)

**Comment by riverbaymark** [comment]
Seeing something similar on bar charts.   The bars are the same color as the background.

**Comment by AppPear** [comment]
@rmbeaty It's fixed it will be released soon
