### ISSUE TITLE
Horizontal lines and labels hidden when navigate

### ISSUE THREAD

**Issue by muayyadayesh** [AppPear/ChartView#52]
An issue is happening with LineView when trying to perform a navigation link then going back for parent view, labels and horizontal lines are hidden..
![Screen Shot 2020-03-04 at 1 42 00 PM](https://user-images.githubusercontent.com/31501126/75866089-f70b5900-5e1d-11ea-8b3a-ff43430dc4bd.png)

**Comment by AppPear** [comment]
Hi, thanks for the catch I fixed it, should be working fine with the latest release.
