### ISSUE TITLE
only go to 99.9

### ISSUE THREAD

**Issue by janbildsoehansen** [AppPear/ChartView#55]
hey nice work i'm having issues making the chart show numbers over 100 
it only show data values to 99.9 how to make it go over 100.0..??
thanks

**Comment by AppPear** [comment]
Hi, I'm not sure if I understand, a dataset with over a 100 pieces or a value over a 100?
I can show values over a 100 without a problem
![Simulator Screen Shot - iPhone 11 Pro - 2020-03-06 at 12 21 04](https://user-images.githubusercontent.com/2826764/76079559-32845f80-5fa5-11ea-8c0d-9e64032cc3f4.png)

**Comment by janbildsoehansen** [comment]
ya okay might be my file formater then that dont pas numbers over 100 Hmm..
