### ISSUE TITLE
Multiple LineViews in Vstack/ScrollView

### ISSUE THREAD

**Issue by thedc89** [AppPear/ChartView#60]
First of all - thanks for creating this library, it's awesome!💥

I'd like to out have a few LineViews inside a Vstack or ScrollView. Unfortunately, I'm not sure what is the best way to accomplish that without some layout issues. (please take note I'm fairly new to SwiftUI :))

When I put them in Vstack, they got squeezed like so:

```
 var body: some View {

    VStack(alignment: .leading, spacing: 20) {

      LineView(data: [8,23,54,32,12,37,7,23,43], title: "Line chart", legend: "Full screen")
      LineView(data: [8,23,54,32,12,37,7,23,43], title: "Line chart", legend: "Full screen")
      LineView(data: [8,23,54,32,12,37,7,23,43], title: "Line chart", legend: "Full screen")
```
<a href="https://imgur.com/mYLZ2W9"><img src="https://i.imgur.com/mYLZ2W9.png" title="source: imgur.com" /></a>

When I wrap the above in a ScrollView, I get the following layout and touch event is no longer being detected on the chart:

```
var body: some View {

 ScrollView(.vertical, showsIndicators: false) {

   VStack(alignment: .leading, spacing: 20) {
      LineView(data: [8,23,54,32,12,37,7,23,43], title: "Line chart", legend: "Full screen")
       LineView(data: [8,23,54,32,12,37,7,23,43], title: "Line chart", legend: "Full screen")
```

<a href="https://imgur.com/7UM389L"><img src="https://i.imgur.com/7UM389L.png" title="source: imgur.com" /></a>

I haven't found any related issue here (maybe I overlooked something), so maybe that's not a bug but just me doing something wrong :) 

Let me know if you have an idea what the best approach is ;)

**Comment by AppPear** [comment]
Hi, you probably need to add a frame to them to display properly like
`LineView(data: [8,23,54,32,12,37,7,23,43], title: "Line chart", legend: "Full screen").frame(width:200, height:300)`

**Comment by thedc89** [comment]
Yup, that helped, thank you!
