### ISSUE TITLE
LineChartView always displays a constant 14

### ISSUE THREAD

**Issue by edutim** [AppPear/ChartView#64]
It appears the LineChartView always displays 14. The struct has an optional value but the initializer force unwraps the parameter causing it to crash if giving the value nil.

**Comment by siddharth952** [comment]
Modify ```rateValue:```

``` LineChartView(data: [8,23,54,32,12,37,7,23,43], title: "Confirmed", legend: "\(noConfirmed)",rateValue: 2)```

**Comment by UniverseFly** [comment]
I encountered the same problem😭

**Comment by rodericj** [comment]
yeah I agree with this: https://github.com/AppPear/ChartView/blob/master/Sources/SwiftUICharts/LineChart/MultiLineChartView.swift#L49. It's probably not wise to force unwrap the optionals. 

I get the sense that v2 might be a big rewrite but I'm happy to take a stab at a fix for this to clean it up.

**Comment by rodericj** [comment]
@UniverseFly @edutim Try the linked PR if you want it.
