### ISSUE TITLE
How to integrate SwiftUICharts in to UIKit existing project. 

### ISSUE THREAD

**Issue by rajeshfintel** [AppPear/ChartView#65]
Hi,
I want to integrate SwiftUICharts in to existing Swift project (This project developed using UIKit, UIViewController) based application.
Please let me know the possible solution.

**Comment by rajeshfintel** [comment]
Finally i found it.

        let childView = UIHostingController(rootView: LineCharts())
        addChild(childView)
        childView.view.frame = viewChatcontainer.bounds
        viewChatcontainer.addSubview(childView.view)

**Comment by aloveric** [comment]
> Finally i found it.
> 
> ```
>     let childView = UIHostingController(rootView: LineCharts())
>     addChild(childView)
>     childView.view.frame = viewChatcontainer.bounds
>     viewChatcontainer.addSubview(childView.view)
> ```

Thanks
