### ISSUE TITLE
LineView's YLegend's values are bit off in the new release

### ISSUE THREAD

**Issue by shah95rukh** [AppPear/ChartView#68]
Hi, I have recently noticed that YLegend's values in the Full-screen line view are a bit off. As you can see in the images attached below, the final point of 161 is below the 161 line.

![IMG_6729](https://user-images.githubusercontent.com/12913466/79697060-85ad2b80-824e-11ea-8c04-5853b75c4170.jpeg)

![IMG_6730](https://user-images.githubusercontent.com/12913466/79697113-cd33b780-824e-11ea-9875-5a05178ac7fc.jpeg)

**Comment by siddharth952** [comment]
Yes, I am facing the same problem as shown.

**Comment by VincentBeee** [comment]
Hi,

Change the following in LineView:

Line()
      frame: .constant(CGRect(x: 0, y: 0, width: reader.frame(in: .local).width - 50, height: reader.frame(in: .local).height **+ 30)**),

Adding the bit of extra height fixed it for me.

**Comment by shah95rukh** [comment]
> Hi,
> 
> Change the following in LineView:
> 
> Line()
> frame: .constant(CGRect(x: 0, y: 0, width: reader.frame(in: .local).width - 50, height: reader.frame(in: .local).height **+ 30)**),
> 
> Adding the bit of extra height fixed it for me.

Thanks! this does fix the issue.
