### ISSUE TITLE
Custom dropshadow and size

### ISSUE THREAD

**Issue by Seitenwerk** [AppPear/ChartView#7]
Hey, first: The charts look awesome!

But I wonder if it is possible to remove the drop shadow and make the chart fullscreen? At least  being able to make a custom size for the line chart would be very nice.

While I like the idea of those small cards, the charts look and behave too good not to use them as full blown charts inside an app.

**Comment by AppPear** [comment]
Hi, thanks! I haven't published a full screen linechart view yet, tho I have this prototype, check out: 
https://twitter.com/sandris96/status/1168962872111771648?s=20
I can share it if you wish

**Comment by Seitenwerk** [comment]
That’s amazing! I actually started trying to create a similar variant based on your work but it seems like you were already working on exactly what I had in mind. :) 

Still learning how to work with those touch events in SwiftUI. If there is something you can share, I would be happy to get inspiration from that.

**Comment by bingimar** [comment]
yes, fantastic charts!!

I also would like to remove the drop shadow.

**Comment by wildfang** [comment]
Any news on this? The graphs look fantastic but the current form (shadow + size) is not what I need...

**Comment by ramzzzay** [comment]
@AppPear awesome chars! Any news about full screen mode ?

**Comment by AppPear** [comment]
Hi, added full screen line chart (LineView) also added the option to turn off drop shadow check out the readme. Will add custom drop shadow size soon. Stay tuned!

**Comment by wildfang** [comment]
After updating to 1.4.0, I can not compile anymore.. Error:

/Library/Developer/Xcode/DerivedData/TestChartViews-clbxmdavqalfeieqqijfuouqgezb/SourcePackages/checkouts/ChartView/Sources/SwiftUICharts/LineChart/Legend.swift:32:33: Reference to property 'colorScheme' in closure requires explicit 'self.' to make capture semantics explicit

**Comment by ramzzzay** [comment]
@wildfang same for me, I've just added `self.` for fast fix, but got another problem from my issue.

**Comment by AppPear** [comment]
Thanks I’m going to look into that

**Comment by AppPear** [comment]
Should be fixed by 1.4.1
