### ISSUE TITLE
DarkMode Bar Chart is always OrangeDark

### ISSUE THREAD

**Issue by dahlboy** [AppPear/ChartView#72]
I created a bar chart with the example provided and specified a custom bar chart color
BarChartView(data: ChartData(values: [("2018 Q4",63150), ("2019 Q1",50900), ("2019 Q2",77550), ("2019 Q3",79600), ("2019 Q4",92550)]), title: "Sales", legend: "Quarterly", style: Styles.barChartStyleNeonBlueLight)

It works as expected in LightMode
![image](https://user-images.githubusercontent.com/64939726/81314475-01c0b500-903e-11ea-9125-1ce484039f5c.png)

However, when I switch to DarkMode, the bar chart seems to always be OrangeDark
![image](https://user-images.githubusercontent.com/64939726/81314535-169d4880-903e-11ea-8e5b-28744adb7129.png)

**Comment by yumsmools** [comment]
Hi there
any update here.  I'm having the same issue

**Comment by satan87** [comment]
Hello,

it is actually working, but you need to set it up manually.

```
struct TestDarkMode: View {
    
    var style: ChartStyle {
        let st = Styles.barChartStyleNeonBlueLight
        st.darkModeStyle = Styles.barChartStyleNeonBlueDark
        return st
    }
    
    var body: some View {
        BarChartView(
            data: ChartData(values:
                [("2018 Q4",63150),
                 ("2019 Q1",50900),
                 ("2019 Q2",77550), ("2019 Q3",79600), ("2019 Q4",92550)]),
            title: "Sales",
            legend: "Quarterly",
            style: style)
    }
    
}
```

var style: ChartStyle {
        let st = Styles.barChartStyleNeonBlue**Light**
        **st.darkModeStyle = Styles.barChartStyleNeonBlueDark**
        return st
    }


This should show the graph in DarkMode.

**Comment by dahlboy** [comment]
Thanks so much for the snippet! I'm relatively new to swift and was able to get my code to work with the example. I'll close this issue.
