### ISSUE TITLE
Great project but seems dead??

### ISSUE THREAD

**Issue by LucasCarioca** [AppPear/ChartView#86]
I really like this project but it seems like even with a decent following and contributions it is dead. 5 prs pending with one sitting for over a month.

Thinking about contributing but not if prs will just sit.

I suggest adding maintainers or supporting the project more actively. Glad to help if I can.

**Comment by Quantum2** [comment]
Agreed, no point in contributing if there is no one around to merge good PR's

**Comment by LucasCarioca** [comment]
Such a shame. This is the only decent chart package for swiftui that I have found so far.

**Comment by martinstoyanov** [comment]
cc @AppPear

**Comment by AppPear** [comment]
I take a look at them on the weekend I just started working at a new place took a bit of my time recently

**Comment by LucasCarioca** [comment]
No worries. I would recommend maybe adding some people to help out. This project has good potential.

**Comment by AdrianBinDC** [comment]
@AppPear Hey there! I pulled down your code and poked around. If I throw some size customization in, do you think you'll be able to get around to merging it if it's good to go? Looking at `Helpers.swift` L133...here's what's there right now.

```
public struct ChartForm {
    #if os(watchOS)
    public static let small = CGSize(width:120, height:90)
    public static let medium = CGSize(width:120, height:160)
    public static let large = CGSize(width:180, height:90)
    public static let detail = CGSize(width:180, height:160)
    #else
    public static let small = CGSize(width:180, height:120)
    public static let medium = CGSize(width:180, height:240)
    public static let large = CGSize(width:360, height:120)
    public static let detail = CGSize(width:180, height:120)
    #endif
}
```

**Comment by AppPear** [comment]
A version 2.0 is coming soon, so please hold off your PRs for a while. I'm writing a new code base with more sleek code architecture with an option for easier expansion. I'll make beta releases so you can test betas, also soon I'll make issues for this new release so if you'd like, you can contribute so it can be released quicker. More info: https://github.com/AppPear/ChartView/pull/89

**Comment by AdrianBinDC** [comment]
Cool! I'll keep my eyes peeled for it. Hopefully it incorporates custom frame sizes :)

**Comment by AppPear** [comment]
it will :)
