### ISSUE TITLE
Create interaction for PieChart

### ISSUE THREAD

**Issue by AppPear** [AppPear/ChartView#97]
# v2 ticket

## Ticket description:

Create a touch interaction for PieChart

* scale the touched slice up a bit for the duration of the touch
* if you slide over your finger to another slice it the new one should scale up and the old should scale back to original

**Comment by Lebron1992** [comment]
@AppPear  I'd like to implement the feature. 😄

**Comment by AppPear** [comment]
thanks, please if you are ready create a PR

**Comment by Lebron1992** [comment]
The feature is finished, so the issue could be closed.
