### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by LucasCarioca** [AppPear/ChartView#99]
# v2 ticket

## Ticket description:
We should try to standardize in code documentation for this project. If we do, we can then auto generate docs from the code. 

Possible doc generation https://github.com/SwiftDocOrg/swift-doc

Info on in code documentation: https://sarunw.com/posts/swift-documentation/

**Comment by LucasCarioca** [comment]
Thoughts? Alternatives?

**Comment by LucasCarioca** [comment]
Thoughts? Alternatives?

**Comment by satan87** [comment]
When you Command+Clcik on a method, Xcode can add the documentation for you.
    /// <#Description#>
    /// - Parameters:
    ///   - startPoint: <#startPoint description#>
    ///   - endPoint: <#endPoint description#>
    /// - Returns: <#description#>

Example:
    /// Convenience method to return a LinearGradient from the ColorGradient
    /// - Parameters:
    ///   - startPoint: starting point
    ///   - endPoint: ending point
    /// - Returns: a Linear gradient

<img width="526" alt="Screen Shot 2020-05-24 at 4 31 32 PM" src="https://user-images.githubusercontent.com/5104971/82764350-0924e400-9ddc-11ea-8517-ba1e82edf980.png">

We could start with that?

Nicolas

**Comment by LucasCarioca** [comment]
Yeah exactly. That swift doc project just reads the code and makes a md or html files of that documentation to be published as github pages. 

We could just start by making sure to include documentation (like you showed) with every change.

**Comment by danwood** [comment]
I can work on this for a bit. Not sure how to assign this to myself or how to move the card in the column view....
